# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("PHOTO_VETTING", "Fotoğraf Doğrulama (WasteReport)"),
                            (
                                "DETECTIVE_ANALYSIS",
                                "Fotoğraf Analizi (DetectiveReport)",
                            ),
                            ("AI_COACH", "AI Davranış Koçu"),
                            ("PRIORITY_ADVISOR", "Öncelik Danışmanı"),
                            ("SMART_CATEGORIZE", "Akıllı Kategorizasyon"),
                            ("CARBON_CALC", "Karbon Hesaplama"),
                        ],
                        max_length=40,
                        verbose_name="Özellik",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Örn: gpt-4o-mini, gpt-4o",
                        max_length=30,
                        verbose_name="Kullanılan Model",
                    ),
                ),
                (
                    "tokens_input",
                    models.PositiveIntegerField(verbose_name="Girdi Token"),
                ),
                (
                    "tokens_output",
                    models.PositiveIntegerField(verbose_name="Çıktı Token"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="(tokens_input * input_price + tokens_output * output_price) / 1_000_000",
                        max_digits=10,
                        verbose_name="Maliyet (USD)",
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        help_text="API çağrısının toplam süresi. Latency takibi için.",
                        verbose_name="Yanıt Süresi (ms)",
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Başarılı")),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="API hata döndürdüyse: rate_limit_error, invalid_api_key, vb.",
                        max_length=50,
                        verbose_name="Hata Kodu",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="İlişkili Nesne Türü"
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="İlişkili Nesne ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sistem otomatik çağrıları için None (koç mesajları hariç).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Analiz Günlüğü",
                "verbose_name_plural": "AI Analiz Günlükleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_ailog_user_date"
                    ),
                    models.Index(
                        fields=["feature", "-created_at"], name="idx_ailog_feature_date"
                    ),
                    models.Index(
                        fields=["success", "-created_at"], name="idx_ailog_success_date"
                    ),
                    models.Index(
                        fields=["model_used", "-created_at"],
                        name="idx_ailog_model_date",
                    ),
                ],
            },
        ),
    ]
