# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="Üniversite öğrenci numarası. Personel için boş bırakılabilir.",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Öğrenci Numarası",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Bölüm bazlı atık analizi ve ısı haritası için.",
                        max_length=100,
                        verbose_name="Bölüm",
                    ),
                ),
                (
                    "trust_score",
                    models.SmallIntegerField(
                        default=50,
                        help_text="Suistimal önleme skoru. Yeni kullanıcılar 50 ile başlar. Onaylı bildirimler artırır, reddedilen bildirimler düşürür.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Güven Puanı",
                    ),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalize liderlik tablosu sayacı. Doğrudan güncelleme yapma — PointTransaction üzerinden yönetilir.",
                        verbose_name="Toplam Puan",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Öğrenci"),
                            ("STAFF", "Personel"),
                            ("ADMIN", "Yönetici"),
                        ],
                        default="STUDENT",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserTrustLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delta",
                    models.SmallIntegerField(
                        help_text="Pozitif: artış, Negatif: düşüş. Örn: +2, -5",
                        verbose_name="Değişim",
                    ),
                ),
                (
                    "score_after",
                    models.SmallIntegerField(
                        help_text="Güncelleme sonrasındaki trust_score snapshot'ı.",
                        verbose_name="Değişim Sonrası Skor",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("REPORT_APPROVED", "Bildirim Onaylandı"),
                            ("REPORT_REJECTED", "Bildirim Reddedildi"),
                            ("VETTING_CORRECT", "Denetim Oyu Doğru"),
                            ("VETTING_WRONG", "Denetim Oyu Yanlış"),
                            ("OBSERVATION_MODE", "Gözlem Modu Uygulandı"),
                            ("STREAK_BONUS", "30 Günlük Temiz Seri"),
                            ("MANUAL_ADJUSTMENT", "Manuel Düzeltme"),
                            ("DETECTIVE_CONFIRMED", "Dedektif Raporu Doğrulandı"),
                        ],
                        max_length=50,
                        verbose_name="Sebep",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Hangi modelden tetiklendi. Örn: WasteReport, DetectiveReport",
                        max_length=50,
                        verbose_name="İlişkili Nesne Türü",
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="İlgili kaydın UUID'si. Audit trail için.",
                        null=True,
                        verbose_name="İlişkili Nesne ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güven Günlüğü",
                "verbose_name_plural": "Güven Günlükleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="idx_user_role_active"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["student_id"], name="idx_user_student_id"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-total_points"], name="idx_user_total_points"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["department"], name="idx_user_department"),
        ),
        migrations.AddIndex(
            model_name="usertrustlog",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_trustlog_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="usertrustlog",
            index=models.Index(
                fields=["reason", "-created_at"], name="idx_trustlog_reason_date"
            ),
        ),
    ]
