# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "waste_category",
                    models.CharField(
                        choices=[
                            ("PAPER", "Kağıt / Karton"),
                            ("PLASTIC", "Plastik"),
                            ("GLASS", "Cam"),
                            ("ORGANIC", "Organik"),
                            ("ELECTRONIC", "Elektronik"),
                            ("GENERAL", "Genel / Karışık"),
                            ("SMALL", "Küçük (İzmarit vb.)"),
                        ],
                        max_length=30,
                        verbose_name="Atık Kategorisi",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Fotoğraf"),
                            ("QR", "QR Kod"),
                            ("BOTH", "Fotoğraf + QR"),
                        ],
                        max_length=20,
                        verbose_name="Doğrulama Yöntemi",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Enlem"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Boylam"
                    ),
                ),
                (
                    "geo_distance_meters",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Kullanıcı koordinatı ile kutu koordinatı arasındaki mesafe.",
                        verbose_name="Kutuya Mesafe (Metre)",
                    ),
                ),
                (
                    "fill_delta",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Bu rapor onaylandığında kutunun fill_level değerine eklenecek miktar. Formül: base_volume × decay_correction",
                        max_digits=4,
                        verbose_name="Doluluk Artışı",
                    ),
                ),
                (
                    "suspicion_score",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0-100 arası. ≥40 kitle denetimine gönderir, ≥100 otomatik reddeder.",
                        verbose_name="Şüphe Skoru",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("APPROVED", "Onaylandı"),
                            ("REJECTED", "Reddedildi"),
                            ("UNDER_VETTING", "Kitle Denetiminde"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "points_awarded",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Onay sonrası verilen puan. Gecikmeli puanlama için 0 olabilir.",
                        verbose_name="Verilen Puan",
                    ),
                ),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        help_text="Kullanıcı cihazının bildirimi BAŞLATTIĞI an. Offline sync için: sunucu bu değeri iş mantığında baz alır. Güvenlik: Sunucu zamanından 24 saat farklıysa bildirim reddedilir.",
                        verbose_name="İstemci Zaman Damgası",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Sunucu Alım Zamanı"
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_reports",
                        to="campus.bin",
                        verbose_name="Çöp Kutusu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="SET_NULL: Kullanıcı silinse bile rapor istatistiklerde kalır.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atık Bildirimi",
                "verbose_name_plural": "Atık Bildirimleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VettingVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("APPROVE", "Onayla"), ("REJECT", "Reddet")],
                        max_length=10,
                        verbose_name="Oy",
                    ),
                ),
                (
                    "voter_trust_at_vote",
                    models.SmallIntegerField(
                        help_text="Snapshot. Sonradan trust değişirse bu oyu etkilemez.",
                        verbose_name="Denetçinin Oy Anındaki Trust Skoru",
                    ),
                ),
                (
                    "voter_distance_meters",
                    models.SmallIntegerField(
                        default=0, verbose_name="Denetçinin Kutuya Uzaklığı (Metre)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oy Zamanı"),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetting_votes_cast",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Denetçi",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetting_votes",
                        to="reports.wastereport",
                        verbose_name="Bildirim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denetim Oyu",
                "verbose_name_plural": "Denetim Oyları",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Media storage path. Örn: reports/2024/01/uuid.jpg",
                        max_length=500,
                        verbose_name="Fotoğraf Yolu",
                    ),
                ),
                (
                    "image_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Tekrar kullanım tespiti için SHA256 parmak izi.",
                        max_length=64,
                        verbose_name="Fotoğraf Hash (SHA256)",
                    ),
                ),
                (
                    "ai_bin_detected",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="AI: Kutu Tespit Edildi mi?"
                    ),
                ),
                (
                    "ai_waste_detected",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="AI: Atık Tespit Edildi mi?"
                    ),
                ),
                (
                    "ai_category_suggestion",
                    models.CharField(
                        blank=True,
                        help_text="Vision API'nin önerdiği atık kategorisi. Kullanıcı seçimiyle karşılaştırılır.",
                        max_length=30,
                        verbose_name="AI: Önerilen Kategori",
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="0.000 - 1.000 arası. 0.500 altı düşük güven → suspicion_score artar.",
                        max_digits=4,
                        null=True,
                        verbose_name="AI: Güven Skoru",
                    ),
                ),
                (
                    "ai_is_stock_photo",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="AI: Stok Fotoğraf mı?"
                    ),
                ),
                (
                    "ai_raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="OpenAI API'nin tam JSON yanıtı. Debug ve audit için saklanır.",
                        null=True,
                        verbose_name="AI: Ham Yanıt",
                    ),
                ),
                (
                    "ai_analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="None ise analiz henüz yapılmamış (Celery kuyruğunda).",
                        null=True,
                        verbose_name="AI Analiz Zamanı",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_evidence",
                        to="reports.wastereport",
                        verbose_name="Atık Bildirimi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotoğraf Kanıtı",
                "verbose_name_plural": "Fotoğraf Kanıtları",
            },
        ),
        migrations.AddIndex(
            model_name="wastereport",
            index=models.Index(
                fields=["bin", "-created_at"], name="idx_report_bin_date"
            ),
        ),
        migrations.AddIndex(
            model_name="wastereport",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_report_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="wastereport",
            index=models.Index(
                fields=["user", "bin", "-client_timestamp"], name="idx_report_ratelock"
            ),
        ),
        migrations.AddIndex(
            model_name="wastereport",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_report_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="wastereport",
            index=models.Index(
                fields=["-suspicion_score"], name="idx_report_suspicion"
            ),
        ),
        migrations.AddIndex(
            model_name="wastereport",
            index=models.Index(
                fields=["bin", "status", "-client_timestamp"], name="idx_report_anomaly"
            ),
        ),
        migrations.AddIndex(
            model_name="vettingvote",
            index=models.Index(
                fields=["report", "vote"], name="idx_vetting_report_vote"
            ),
        ),
        migrations.AddIndex(
            model_name="vettingvote",
            index=models.Index(
                fields=["voter", "-created_at"], name="idx_vetting_voter_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="vettingvote",
            constraint=models.UniqueConstraint(
                fields=("report", "voter"), name="unique_vetting_vote_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="photoevidence",
            index=models.Index(
                fields=["image_hash", "-created_at"], name="idx_photo_hash_date"
            ),
        ),
        migrations.AddIndex(
            model_name="photoevidence",
            index=models.Index(fields=["ai_analyzed_at"], name="idx_photo_analyzed"),
        ),
    ]
