# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bina Adı")),
                (
                    "code",
                    models.CharField(
                        help_text="Kısa, benzersiz kod. Örn: MF-A, KUTUPHANE, B-BLOK",
                        max_length=20,
                        unique=True,
                        verbose_name="Bina Kodu",
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("FACULTY", "Fakülte"),
                            ("DORM", "Yurt"),
                            ("CAFETERIA", "Kafeterya / Yemekhane"),
                            ("LIBRARY", "Kütüphane"),
                            ("OUTDOOR", "Açık Alan"),
                            ("OTHER", "Diğer"),
                        ],
                        default="OTHER",
                        max_length=30,
                        verbose_name="Bina Türü",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Enlem"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Boylam"
                    ),
                ),
                (
                    "is_indoor",
                    models.BooleanField(
                        default=True,
                        help_text="True ise bu binadaki kutular için geo-fence eşiği SystemSetting.GEO_FENCE_RADIUS_INDOOR_METERS kullanılır.",
                        verbose_name="İç Mekan mı?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Bina",
                "verbose_name_plural": "Binalar",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["building_type"], name="idx_building_type"),
                    models.Index(fields=["is_active"], name="idx_building_active"),
                    models.Index(
                        fields=["latitude", "longitude"], name="idx_building_coords"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="QR kod içeriği. Mobil uygulama bu UUID'yi okur.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="İnsan okunabilir kod. Örn: BIN-MF-A-01",
                        max_length=20,
                        unique=True,
                        verbose_name="Kutu Kodu",
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        help_text="Temizlik personeli için fiziksel yön tarifi. Örn: 'A Blok giriş kapısı sağı'",
                        max_length=200,
                        verbose_name="Konum Açıklaması",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Enlem"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Boylam"
                    ),
                ),
                (
                    "bin_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Genel Atık"),
                            ("RECYCLABLE", "Geri Dönüşüm (Karma)"),
                            ("ORGANIC", "Organik"),
                            ("GLASS", "Cam"),
                            ("ELECTRONIC", "Elektronik"),
                            ("PAPER", "Kağıt"),
                        ],
                        default="GENERAL",
                        max_length=30,
                        verbose_name="Kutu Türü",
                    ),
                ),
                (
                    "capacity_liters",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Fiziksel hacim. fill_level kalibrasyonunda kullanılır. İleride kapasiteye göre fill_delta normalleştirilebilir.",
                        verbose_name="Kapasite (Litre)",
                    ),
                ),
                (
                    "fill_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="0.000 = boş, 1.000 = taşıyor. Asla doğrudan güncelleme yapma; Bin.add_fill() metodunu kullan.",
                        max_digits=4,
                        verbose_name="Doluluk",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Aktif"),
                            ("MAINTENANCE", "Bakımda"),
                            ("REMOVED", "Kaldırıldı"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "last_emptied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Boşaltma"
                    ),
                ),
                (
                    "last_report_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Bildirim"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dış mekan kutuları için boş bırakılabilir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bins",
                        to="campus.building",
                        verbose_name="Bina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çöp Kutusu",
                "verbose_name_plural": "Çöp Kutuları",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BinStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fill_level",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        verbose_name="Doluluk Anlık Değeri",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("REPORT", "Kullanıcı Bildirimi"),
                            ("EMPTIED", "Boşaltıldı"),
                            ("DECAY_CORRECTION", "Sıkışma Düzeltmesi"),
                            ("MANUAL", "Manuel Güncelleme"),
                        ],
                        max_length=30,
                        verbose_name="Tetikleyici",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="campus.bin",
                        verbose_name="Çöp Kutusu",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bin_status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tetikleyen Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kutu Durum Günlüğü",
                "verbose_name_plural": "Kutu Durum Günlükleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["bin", "-created_at"], name="idx_binlog_bin_date"
                    ),
                    models.Index(
                        fields=["trigger", "-created_at"],
                        name="idx_binlog_trigger_date",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(
                fields=["status", "is_active"], name="idx_bin_status_active"
            ),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(fields=["-fill_level"], name="idx_bin_fill_level"),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(fields=["latitude", "longitude"], name="idx_bin_coords"),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(fields=["last_emptied_at"], name="idx_bin_last_emptied"),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(fields=["last_report_at"], name="idx_bin_last_report"),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(fields=["building"], name="idx_bin_building"),
        ),
    ]
