# Generated by Django 6.0.2 on 2026-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="SCREAMING_SNAKE_CASE. Örn: GEO_FENCE_RADIUS_METERS",
                        max_length=100,
                        unique=True,
                        verbose_name="Anahtar",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Her zaman string. value_type alanına göre parse edilir.",
                        max_length=500,
                        verbose_name="Değer",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INT", "Tam Sayı"),
                            ("FLOAT", "Ondalık Sayı"),
                            ("BOOL", "Mantıksal (true/false)"),
                            ("STRING", "Metin"),
                        ],
                        default="STRING",
                        max_length=20,
                        verbose_name="Değer Tipi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Bu ayar ne işe yarar? Hangi modülü etkiler?",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
            ],
            options={
                "verbose_name": "Sistem Ayarı",
                "verbose_name_plural": "Sistem Ayarları",
                "ordering": ["key"],
            },
        ),
    ]
