# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campus", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bounty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "bounty_type",
                    models.CharField(
                        choices=[
                            ("AUTO", "Sistem Otomatik"),
                            ("MANUAL", "Admin / Personel"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="Görev Türü",
                    ),
                ),
                (
                    "target_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Hedef Enlem",
                    ),
                ),
                (
                    "target_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Hedef Boylam",
                    ),
                ),
                (
                    "target_radius_meters",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Bölgesel görevlerde geçerli hedef alanı tanımlar.",
                        null=True,
                        verbose_name="Hedef Yarıçap (Metre)",
                    ),
                ),
                (
                    "reward_points",
                    models.PositiveSmallIntegerField(verbose_name="Ödül Puanı"),
                ),
                (
                    "max_claimants",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="İlk kaç kişi ödül alır? Puan enflasyonunu önler.",
                        verbose_name="Maksimum Kazanan",
                    ),
                ),
                (
                    "current_claimants",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Denormalize sayaç. Manuel güncelleme yapma. BountyClaim oluşturulunca F() ile atomik artar.",
                        verbose_name="Mevcut Kazanan Sayısı",
                    ),
                ),
                (
                    "required_waste_category",
                    models.CharField(
                        blank=True,
                        help_text="Boş ise tüm kategoriler geçerli.",
                        max_length=30,
                        verbose_name="Gerekli Atık Kategorisi",
                    ),
                ),
                (
                    "min_reports_required",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Minimum Bildirim Sayısı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Açık"),
                            ("CLOSED", "Kapalı"),
                            ("EXPIRED", "Süresi Doldu"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Bitiş Zamanı")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="None = sistem otomatik oluşturdu.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bounties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "target_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounties",
                        to="campus.bin",
                        verbose_name="Hedef Kutu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty Görevi",
                "verbose_name_plural": "Bounty Görevleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BountyClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_awarded",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Bounty.reward_points'ten kopyalanır. Sonradan bounty değişirse etkilenmez.",
                        verbose_name="Verilen Puan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("AWARDED", "Ödüllendirildi"),
                            ("REJECTED", "Reddedildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Talep Zamanı"
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ödül Zamanı"
                    ),
                ),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="bounties.bounty",
                        verbose_name="Görev",
                    ),
                ),
                (
                    "qualifying_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bounty_claims",
                        to="reports.wastereport",
                        verbose_name="Tamamlayıcı Bildirim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounty_claims",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bounty Talebi",
                "verbose_name_plural": "Bounty Talepleri",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["status", "expires_at"], name="idx_bounty_status_expiry"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["bounty_type", "status"], name="idx_bounty_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(
                fields=["target_bin", "status"], name="idx_bounty_bin_status"
            ),
        ),
        migrations.AddIndex(
            model_name="bountyclaim",
            index=models.Index(
                fields=["bounty", "status"], name="idx_claim_bounty_status"
            ),
        ),
        migrations.AddIndex(
            model_name="bountyclaim",
            index=models.Index(
                fields=["user", "-claimed_at"], name="idx_claim_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="bountyclaim",
            index=models.Index(
                fields=["status", "-claimed_at"], name="idx_claim_status_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="bountyclaim",
            constraint=models.UniqueConstraint(
                fields=("bounty", "user"), name="unique_bounty_claim_per_user"
            ),
        ),
    ]
