# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectiveReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("LITTERING", "Yere Atılmış Atık"),
                            ("OVERFLOWING", "Taşmış / Açık Kutu"),
                            ("WRONG_SORT", "Yanlış Ayrıştırma"),
                            ("DAMAGED_BIN", "Hasarlı Kutu"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=30,
                        verbose_name="Sorun Türü",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Enlem"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Boylam"
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Fotoğraf Yolu"
                    ),
                ),
                (
                    "image_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Fotoğraf Hash",
                    ),
                ),
                (
                    "ai_problem_detected",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="AI: Sorun Tespit Edildi mi?",
                    ),
                ),
                (
                    "ai_problem_type_suggestion",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="AI: Önerilen Sorun Türü",
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="AI: Güven Skoru",
                    ),
                ),
                (
                    "ai_raw_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI: Ham Yanıt"
                    ),
                ),
                (
                    "confirmation_count",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Denormalize sayaç. Harita pin boyutu ve rengi için. DetectiveVote.save() sinyaliyle güncellenir.",
                        verbose_name="Doğrulama Sayısı",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Beklemede"),
                            ("CONFIRMED", "Doğrulandı"),
                            ("RESOLVED", "Çözüldü"),
                            ("REJECTED", "Reddedildi"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "points_awarded",
                    models.SmallIntegerField(default=0, verbose_name="Verilen Puan"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çözülme Zamanı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "nearest_bin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coğrafi hesaplamayla otomatik doldurulur.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detective_reports",
                        to="campus.bin",
                        verbose_name="En Yakın Kutu",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detective_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bildiren",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_detective_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çözen Personel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dedektif Raporu",
                "verbose_name_plural": "Dedektif Raporları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectiveVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("CONFIRM", "Doğruluyorum"),
                            ("REJECT", "Göremedim / Yanlış"),
                        ],
                        max_length=10,
                        verbose_name="Oy",
                    ),
                ),
                (
                    "voter_distance_meters",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Oy verenin sorun noktasına yakınlığı. Ağırlık hesabında kullanılır.",
                        verbose_name="Oy Veren Kişinin Mesafesi (Metre)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oy Zamanı"),
                ),
                (
                    "detective_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="detective.detectivereport",
                        verbose_name="Dedektif Raporu",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detective_votes_cast",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oy Veren",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dedektif Oyu",
                "verbose_name_plural": "Dedektif Oyları",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="detectivereport",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_detrep_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="detectivereport",
            index=models.Index(
                fields=["latitude", "longitude"], name="idx_detrep_coords"
            ),
        ),
        migrations.AddIndex(
            model_name="detectivereport",
            index=models.Index(
                fields=["nearest_bin", "status"], name="idx_detrep_bin_status"
            ),
        ),
        migrations.AddIndex(
            model_name="detectivereport",
            index=models.Index(
                fields=["reporter", "-created_at"], name="idx_detrep_reporter"
            ),
        ),
        migrations.AddIndex(
            model_name="detectivereport",
            index=models.Index(fields=["resolved_at"], name="idx_detrep_resolved"),
        ),
        migrations.AddIndex(
            model_name="detectivevote",
            index=models.Index(
                fields=["detective_report", "vote"], name="idx_detvote_report_vote"
            ),
        ),
        migrations.AddIndex(
            model_name="detectivevote",
            index=models.Index(
                fields=["voter", "-created_at"], name="idx_detvote_voter_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="detectivevote",
            constraint=models.UniqueConstraint(
                fields=("detective_report", "voter"),
                name="unique_detective_vote_per_user",
            ),
        ),
    ]
