# Generated by Django 6.0.2 on 2026-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detective", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectivereport",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="detectivereport",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="detective_photos/",
                verbose_name="Fotoğraf",
            ),
        ),
    ]
