# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Örn: FIRST_REPORT, DETECTIVE_10, WEEKLY_HERO",
                        max_length=50,
                        unique=True,
                        verbose_name="Rozet Kodu",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rozet Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon_path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="İkon Yolu"
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("MILESTONE", "Kilometre Taşı"),
                            ("WEEKLY", "Haftalık"),
                            ("SPECIAL", "Özel"),
                            ("DETECTIVE", "Dedektif"),
                            ("VETTING", "Denetçi"),
                            ("BOUNTY", "Bounty Avcısı"),
                        ],
                        default="MILESTONE",
                        max_length=30,
                        verbose_name="Rozet Türü",
                    ),
                ),
                (
                    "required_points",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Dolu ise: Bu puana ulaşınca otomatik verilir. Boş ise: Eylem bazlı.",
                        null=True,
                        verbose_name="Gereken Puan",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Rozet",
                "verbose_name_plural": "Rozetler",
                "ordering": ["badge_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["badge_type", "is_active"], name="idx_badge_type_active"
                    ),
                    models.Index(fields=["required_points"], name="idx_badge_points"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(
                        help_text="Pozitif: kazanç. Negatif: düşüş.",
                        verbose_name="Miktar",
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="User.total_points snapshot'ı. Audit ve hata ayıklama için.",
                        verbose_name="İşlem Sonrası Bakiye",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("REPORT_APPROVED", "Bildirim Onaylandı"),
                            ("BOUNTY_CLAIMED", "Bounty Tamamlandı"),
                            ("VETTING_REWARD", "Denetim Ödülü"),
                            ("DETECTIVE_REWARD", "Dedektif Ödülü"),
                            ("DELAYED_BONUS", "Gecikmeli Puan Bonusu"),
                            ("PENALTY", "Ceza"),
                            ("MANUAL_ADJUSTMENT", "Manuel Düzeltme"),
                            ("STREAK_BONUS", "Seri Bonusu"),
                        ],
                        max_length=30,
                        verbose_name="İşlem Türü",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Örn: WasteReport, Bounty, DetectiveReport",
                        max_length=50,
                        verbose_name="İlişkili Nesne Türü",
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="İlişkili Nesne ID"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Manuel düzeltmeler için açıklama.",
                        max_length=200,
                        verbose_name="Not",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zaman"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puan İşlemi",
                "verbose_name_plural": "Puan İşlemleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_ptx_user_date"
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="idx_ptx_type_date",
                    ),
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="idx_ptx_related_object",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kazanılma Zamanı"
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tetikleyen Nesne Türü"
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Tetikleyen Nesne ID"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="gamification.badge",
                        verbose_name="Rozet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Rozeti",
                "verbose_name_plural": "Kullanıcı Rozetleri",
                "ordering": ["-awarded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-awarded_at"], name="idx_userbadge_user_date"
                    ),
                    models.Index(
                        fields=["badge", "-awarded_at"], name="idx_userbadge_badge_date"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge"), name="unique_badge_per_user"
                    )
                ],
            },
        ),
    ]
