# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BIN_WARNING", "Kutu Uyarı Seviyesinde"),
                            ("BIN_CRITICAL", "Kutu Kritik Seviyesinde"),
                            ("BIN_STAGNANT", "Kutu Hareketsiz Kaldı"),
                            ("REPORT_APPROVED", "Bildirim Onaylandı"),
                            ("REPORT_REJECTED", "Bildirim Reddedildi"),
                            ("VETTING_REQUEST", "Denetim Oyu İsteniyor"),
                            ("VETTING_RESOLVED", "Denetim Tamamlandı"),
                            ("BOUNTY_AVAILABLE", "Yakınında Yeni Görev"),
                            ("BOUNTY_AWARDED", "Görev Ödülü Kazanıldı"),
                            ("BOUNTY_EXPIRING", "Görev Süresi Dolmak Üzere"),
                            ("DETECTIVE_CONFIRMED", "Sorun Raporu Doğrulandı"),
                            ("DETECTIVE_RESOLVED", "Bildirdiğin Sorun Çözüldü"),
                            ("TRUST_CHANGE", "Güven Puanı Değişti"),
                            ("BADGE_AWARDED", "Yeni Rozet Kazanıldı"),
                            ("WEEKLY_SUMMARY", "Haftalık Özet"),
                            ("AI_COACH_MESSAGE", "AI Koç Mesajı"),
                        ],
                        max_length=40,
                        verbose_name="Bildirim Türü",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("body", models.TextField(verbose_name="İçerik")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Deep link ve payload için. Örn: {'route': '/bins/uuid/'}",
                        verbose_name="Ek Veri",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                (
                    "is_pushed",
                    models.BooleanField(default=False, verbose_name="Push Gönderildi"),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="İlişkili Nesne Türü"
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="İlişkili Nesne ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="idx_notif_user_unread_date",
                    ),
                    models.Index(
                        fields=["is_pushed", "-created_at"],
                        name="idx_notif_push_pending",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="idx_notif_type_date",
                    ),
                ],
            },
        ),
    ]
